export const stateBrazil = [
  { value: 'AC', label: 'Acre', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/4c/Bandeira_do_Acre.svg' },
  { value: 'AL', label: 'Alagoas', flag: 'https://upload.wikimedia.org/wikipedia/commons/8/88/Bandeira_de_Alagoas.svg' },
  { value: 'AP', label: 'Amapá', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/Bandeira_do_Amapá.svg' },
  { value: 'AM', label: 'Amazonas', flag: 'https://upload.wikimedia.org/wikipedia/commons/6/6b/Bandeira_do_Amazonas.svg' },
  { value: 'BA', label: 'Bahia', flag: 'https://upload.wikimedia.org/wikipedia/commons/2/28/Bandeira_da_Bahia.svg' },
  { value: 'CE', label: 'Ceará', flag: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Bandeira_do_Ceará.svg' },
  { value: 'DF', label: 'Distrito Federal', flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Bandeira_do_Distrito_Federal_%28Brasil%29.svg/243px-Bandeira_do_Distrito_Federal_%28Brasil%29.svg.png' },
  { value: 'ES', label: 'Espírito Santo', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Bandeira_do_Esp%C3%ADrito_Santo.svg' },
  { value: 'GO', label: 'Goiás', flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Flag_of_Goiás.svg/243px-Flag_of_Goiás.svg.png' },
  { value: 'MA', label: 'Maranhão', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Bandeira_do_Maranh%C3%A3o.svg' },
  { value: 'MT', label: 'Mato Grosso', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/0b/Bandeira_de_Mato_Grosso.svg' },
  { value: 'MS', label: 'Mato Grosso do Sul', flag: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Bandeira_de_Mato_Grosso_do_Sul.svg' },
  { value: 'MG', label: 'Minas Gerais', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f4/Bandeira_de_Minas_Gerais.svg' },
  { value: 'PA', label: 'Pará', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Bandeira_do_Par%C3%A1.svg' },
  { value: 'PB', label: 'Paraíba', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Bandeira_da_Para%C3%ADba.svg' },
  { value: 'PR', label: 'Paraná', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Bandeira_do_Paran%C3%A1.svg' },
  { value: 'PE', label: 'Pernambuco', flag: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Bandeira_de_Pernambuco.svg' },
  { value: 'PI', label: 'Piauí', flag: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Bandeira_do_Piau%C3%AD.svg' },
  { value: 'RJ', label: 'Rio de Janeiro', flag: 'https://upload.wikimedia.org/wikipedia/commons/7/73/Bandeira_do_estado_do_Rio_de_Janeiro.svg' },
  { value: 'RN', label: 'Rio Grande do Norte', flag: 'https://upload.wikimedia.org/wikipedia/commons/3/30/Bandeira_do_Rio_Grande_do_Norte.svg' },
  { value: 'RS', label: 'Rio Grande do Sul', flag: 'https://upload.wikimedia.org/wikipedia/commons/6/63/Bandeira_do_Rio_Grande_do_Sul.svg' },
  { value: 'RO', label: 'Rondônia', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Bandeira_de_Rond%C3%B4nia.svg' },
  { value: 'RR', label: 'Roraima', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Bandeira_de_Roraima.svg' },
  { value: 'SC', label: 'Santa Catarina', flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Bandeira_de_Santa_Catarina.svg' },
  { value: 'SP', label: 'São Paulo', flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Bandeira_do_estado_de_São_Paulo.svg/780px-Bandeira_do_estado_de_São_Paulo.svg.png' },
  { value: 'SE', label: 'Sergipe', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/be/Bandeira_de_Sergipe.svg' },
  { value: 'TO', label: 'Tocantins', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Bandeira_do_Tocantins.svg' },
];